---

- name: Set shmmax for postgres
  sysctl:
    name: "kernel.shmmax"
    value: "{{ postgresql_shmmax }}"
    sysctl_set: yes
    state: present
    reload: yes
  when: postgresql_shmmax is defined

- name: Include Ubuntu-specific PostgreSQL installation tasks
  include: install/Ubuntu.yml
  when: "{{ ansible_distribution == 'Ubuntu' }}"
